Fix linkify to only match valid URI characters
IonicaBizau/anser pull request #75
Opened 2024-09-11 12:23 UTC by perlpunk

Fixes #63

It handles the fact that `escapeForHtml` has already been called and matches `&amp;` separately.

I used the RFC (basically the last 5 rules) from:
https://datatracker.ietf.org/doc/html/rfc3986#appendix-A

I tested it with:
```
# "> should be excluded
"https://github.com/os-autoinst/openQA.git"
<https://github.com/os-autoinst/os-autoinst.git>
# () should be included
https://de.wikipedia.org/wiki/Queen_(Band)
# query strings should be included
https://github.com/os-autoinst/openQA?foo=1%20&bar=*2
```

I am not sure how to run the tests. If you give me a hint, I will try and add a test for this.

2024-09-11 13:41 UTC, b10n1k requested changes
I guess you will have to update also the README, DOCUMENTATION.md and not sure if there is any other ref

2024-09-11 15:42 UTC, perlpunk commented
> I guess you will have to update also the README, DOCUMENTATION.md and not sure if there is any other ref

That seems to be generated from the actual function documentation (I hope it's not manually duplicated). And that is often something which is done by the person who releases the library, directly before the release. I prefer to leave such things unless I'm explicitly asked to do it.
@IonicaBizau will tell me :)

2024-09-11 16:10 UTC, okurz approved these changes

2024-09-13 08:31 UTC, Martchus approved these changes

2024-09-22 14:31 UTC, IonicaBizau commented
Thank you very much for fixing this!

2024-09-22 15:22 UTC, perlpunk commented
Hm, it was never merged. I think it's not in the release https://github.com/IonicaBizau/anser/releases/tag/2.2.0

2024-09-26 14:54 UTC, merged